# Chap.-5 Regression-Model training & Evaluation

- ## Simple Linear Regression
    - ### Y = mX + b
    - Where Y = Dependent variable
        - X = Independent variable
        - m = slop (the value represent change in Y for a unit change in X)
        - b = Intercept (value of Y for X = 0)
            
- ## to cal
    - ### S1 : calculate mean of X and mean Y
    - ### S2 : cal deviation in X (X-mean(X))
        - ### cal deviation in Y (Y-mean(Y))
    - ### S3 : cal product of deviation in X and Y : (X-mean(X)) * (Y-mean(Y))
    - ### S4 : cal the square of deviation for X
    
- ## m = sum of product of deviation / sum of square of deviation for X
- ## b = mean of Y - (m * mean of X)

In [ ]:
=A2-$A$17

In [9]:
import pandas as pd
df = pd.read_csv('reg.csv')
df

            x     y        dx    dy     product         dx2      m        b
0   15.000000  49.0 -4.933333  -7.8   38.480000   24.337778  1.893  19.0662
1   23.000000  63.0  3.066667   6.2   19.013333    9.404444    NaN      NaN
2   18.000000  58.0 -1.933333   1.2   -2.320000    3.737778    NaN      NaN
3   23.000000  60.0  3.066667   3.2    9.813333    9.404444    NaN      NaN
4   24.000000  58.0  4.066667   1.2    4.880000   16.537778    NaN      NaN
5   22.000000  61.0  2.066667   4.2    8.680000    4.271111    NaN      NaN
6   22.000000  60.0  2.066667   3.2    6.613333    4.271111    NaN      NaN
7   19.000000  63.0 -0.933333   6.2   -5.786667    0.871111    NaN      NaN
8   19.000000  60.0 -0.933333   3.2   -2.986667    0.871111    NaN      NaN
9   16.000000  52.0 -3.933333  -4.8   18.880000   15.471111    NaN      NaN
10  24.000000  62.0  4.066667   5.2   21.146667   16.537778    NaN      NaN
11  11.000000  30.0 -8.933333 -26.8  239.413333   79.804444    NaN      NaN
12  24.000000  59.0  4.066667   2.2    8.946667   16.537778    NaN      NaN
13  16.000000  49.0 -3.933333  -7.8   30.680000   15.471111    NaN      NaN
14  23.000000  68.0  3.066667  11.2   34.346667    9.404444    NaN      NaN
15  19.933333  56.8       NaN   NaN  429.800000  226.933333    NaN      NaN

In [3]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_csv('reg.csv')

LR = LinearRegression()
LR.fit(df[['x']],df[['y']])

print(LR.coef_)
print(LR.intercept_)

[[1.8939483]]
[19.0472973]

In [10]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_csv('reg.csv')

LR = LinearRegression()
LR.fit(df[['x']],df[['y']])

ypred = LR.predict(df[['x']])
print(ypred)
print('-----------------------')
print(LR.coef_)
print(LR.intercept_)

[[47.45652174]
 [62.60810811]
 [53.13836663]
 [62.60810811]
 [64.5020564 ]
 [60.71415981]
 [60.71415981]
 [55.03231492]
 [55.03231492]
 [49.35047004]
 [64.5020564 ]
 [39.88072856]
 [64.5020564 ]
 [49.35047004]
 [62.60810811]
 [56.79999999]]
-----------------------
[[1.8939483]]
[19.0472973]

In [16]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.DataFrame({'y':[140,155,159,179,192,200,212,215],
                 'X1':[60,62,67,70,71,72,75,78]})
LR = LinearRegression()
LR.fit(df[['y']],df[['X1']])

ypred = LR.predict(df[['y']])
print(ypred)
print('-----------------------')
print(LR.coef_)
print(LR.intercept_)

[[60.50992282]
 [63.71416759]
 [64.56863286]
 [68.84095921]
 [71.61797133]
 [73.32690187]
 [75.89029768]
 [76.53114664]]
-----------------------
[[0.21361632]]
[30.60363837]